name: plugin_pjmei_components_example
description: Demonstrates how to use the plugin_pjmei_components plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0-218.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  plugin_pjmei_components:
    path: ../

dependency_overrides:
  pjmei_white_label_dependencies:
    git:
      url: https://bitbucket.org/olawolffdevs/pjmei_white_label_dependencies
      ref: master
      publish_to: none

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true  
  assets:
    - ../assets/criptografia/